### PR TITLE
Fixed: Command getplayercount

### PR DESCRIPTION
**Pull request by ManifestManah**
Fixed an error that caused the getplayercount command to always return the value 0.
Thanks to Xiazee for helping pinpointing and fixing a similar issue in the past.

### CODE REVIEW

**Comment by ManifestManah** [comment]
Hi Ayuto, I have tried to do as you asked me to, creating two separate pull requests. 

I hope this is what you meant and how you wanted it done, at least I've made the fork, made a commit, and made a pull request. Tried to create a new fork, which threw me back to my current one, I made another commit and went back to attempt to create another pull request which then got combined into this one.

Hopefully, this should do and we can get these bugs smoothened out, there start to be quite a fair amount of users of the Eventscripts Emulator out there, so we try to patch up the bugs we come across and share them on here (^.^)

**Comment by Ayuto** [comment]
Hey, thanks for the PR! Unfortunately, this is still not correct, becuase you created two commits in the same branch (``master``). Usually, you create a fork and then you create a branch for each fix you want to apply. After it has been merged, you can rebase your repository to make it even with this repo. That way you don't have to recreate a fork all the time.

Also, in the second commit you seem to have duplicated the code in ``es_C.py``. I you revert the last commit, I can at least merge the ``getplayercount`` fix.

**Comment by ManifestManah** [comment]
Thank you for pointing it out, I have now reversed the most recent of the changes, now the only fix there is, is for the getplayercount problems. If you accept this change then I'll just make another pull request separate from this one with the fix for forcevalue.

**Comment by Ayuto** [comment]
Thanks!

**Pull request merged**
