### PR TITLE
Fixed to support the new KeyValues.

### PR DESCRIPTION
**Pull request by CookStar**
Still not a problem with the distributed Source.Python, but fixed it ahead of time.

Reference: Source-Python-Dev-Team/Source.Python@89273cd840e601094f31ade3ef601ce3a95f012c

### CODE REVIEW

**Comment by NosferatuJoe** [comment]
I tried this commit on the current SP version but it doesn't seem to work.
I'm getting this:

```
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)
TypeError: not enough arguments for format string
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)
TypeError: not enough arguments for format string
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)
TypeError: not enough arguments for format string
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 187, in command
    if isinstance(command, Command):
NameError: name 'Command' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/plugins/es_emulator/logic.py", line 103, in __call__
    es.addons.callBlock(self.block_name)
  File "../addons/source-python/plugins/es_emulator/eventscripts/es.py", line 356, in callBlock
    self.Blocks[blockname]()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/cmds/__init__.py", line 110, in concommand
    stack.queue([line], 'console', priority=True)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 32, in queue
    self.run()
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 120, in run
    self.command(command, argv, args, exp)
  File "../addons/source-python/plugins/es_emulator/eventscripts/esc/__init__.py", line 217, in command
    self.error(commandname, 'The %s \'%s\' could not be found' % e.args)
TypeError: not enough arguments for format string
```

Will this only work with the upcoming SP update?

**Comment by NosferatuJoe** [comment]
I even tried with an updated SP by downloading the github .zip and overwriting everything but that might not be the way to update it to the latest commit. Can't find documentation on how to do that.

Anyway, same result and here is my sp info now:

```
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 463a8786db851de2f9d62696b037372b
Date          : 2021-04-13 01:22:29.728292
OS            : Linux-5.9.0-1-amd64-x86_64-with-debian-10.9
Game          : csgo
SP version    : None
Github commit : None
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
   01: Metamod:Source 1.11.0-dev+1144
SP plugins:
   00: wcs, 2021.03.30-1, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
--------------------------------------------------------
```

**Comment by NosferatuJoe** [comment]
I just found something in es_emulator.py that states:
```
 # TODO: There is a conflict between ES' and SP's keyvalues module
    import _libs.python.keyvalues as x
    sys.modules['keyvalues'] = x
    es.load('esc')
    es.server.queuecmd('es_load corelib')
```

Might be the reason why it's not working?

**Comment by Ayuto** [comment]
>Will this only work with the upcoming SP update?

Yes!

> 
> 
> I just found something in es_emulator.py that states:
> 
> ```
>  # TODO: There is a conflict between ES' and SP's keyvalues module
>     import _libs.python.keyvalues as x
>     sys.modules['keyvalues'] = x
>     es.load('esc')
>     es.server.queuecmd('es_load corelib')
> ```
> 
> Might be the reason why it's not working?

No, that's the "fix/workaround", so the conflict doesn't have an impact on the emulator.

**Comment by NosferatuJoe** [comment]
So does anyone know how I can update SP to the latest version to see if everything works. I'd like to test & provide feedback if that's okay.

**Comment by Ayuto** [comment]
Right now there is nothing to test. With the next SP release a function will be renamed (``load_from_file2`` to ``from_file_in_place``). The new name is taken into account with @CookStar's PR. So, right now SP and the Emulator use the old name and as soon as I create a new SP release, I will also merge this PR. Then both use the new name.

**Comment by NosferatuJoe** [comment]
> Right now there is nothing to test. With the next SP release a function will be renamed (`load_from_file2` to `from_file_in_place`). The new name is taken into account with @CookStar's PR. So, right now SP and the Emulator use the old name and as soon as I create a new SP release, I will also merge this PR. Then both use the new name.

Bumping this. I think you forgot to merge this PR, just reminding you so that new people using this don't run into issues. Thanks in advance!

**Comment by Ayuto** [comment]
Good point, thank you!

**Pull request merged**
